blog/blueprints/main.py
from flask import render_template, Blueprint, request, flash, redirect, url_for, current_app, abort
from blog.extensions import db
from blog.models import User, Post, Comment, Category
from flask_login import current_user, login_required
from blog.forms.auth import AdminCommentForm, CommentForm, PostForm
from blog.utils import redirect_back
from blog.decorators import permission_required
main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    categories = Category.query.all()
    return render_template('main/index.html', pagination=pagination, posts=posts, categories=categories)


@main_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = 10
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('main/category.html', category=category, pagination=pagination, posts=posts)


@main_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    categories = Category.query.all()
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = 10
    pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.asc()).paginate(
        page, per_page)
    comments = pagination.items

    # if current_user.is_authenticated:
    #     form = AdminCommentForm()
    #     form.author.data = current_user.name
    #     # form.email.data = current_app.config['BLUELOG_EMAIL']
    #     form.site.data = url_for('.index')
    #     from_admin = True
    # else:
    form = CommentForm()


    if form.validate_on_submit():
        body = form.body.data
        comment = Comment(
            author=current_user, body=body, post=post)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
        db.session.add(comment)
        db.session.commit()
        flash('Comment published.', 'success')
        return redirect(url_for('.show_post', post_id=post_id))
    return render_template('main/post.html', post=post, pagination=pagination, form=form, comments=comments, categories=categories)

@main_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    form = PostForm()
    post = Post.query.get_or_404(post_id)
    if current_user != post.author and not current_user.can('MODERATE'):
        abort(403)
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get(form.category.data)
        db.session.commit()
        flash('Post updated.', 'success')
        return redirect(url_for('main.show_post', post_id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    form.category.data = post.category_id
    return render_template('admin/edit_post.html', form=form)

@main_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author and not current_user.can('MODERATE'):
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted.', 'success')
    return redirect_back()

@main_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@permission_required('MODERATE')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Comment deleted.', 'success')
    return redirect_back()

@main_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@permission_required('MODERATE')
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('Comment disabled.', 'success')
    else:
        post.can_comment = True
        flash('Comment enabled.', 'success')
    db.session.commit()
    return redirect_back()

@main_bp.route('/reply/comment/<int:comment_id>')
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        flash('Comment is disabled.', 'warning')
        return redirect(url_for('.show_post', post_id=comment.post.id))
    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')

# @main_bp.route('/search')
# def search():
#     q = request.args.get('q', '')
#     if q == '':
#         flash('Enter keyword about post.', 'warning')
#         return redirect_back()
#
#     category = request.args.get('category', 'post')
#     page = request.args.get('page', 1, type=int)
#     per_page = current_app.config['BLOG_SEARCH_RESULT_PER_PAGE']
#     if category == 'post':
#         pagination = Post.query.whooshee_search(q).paginate(page, per_page)
#     # elif category == 'user':
#     #     pagination = User.query.whooshee_search(q).paginate(page, per_page)
#     elif category == 'comment':
#         pagination = Comment.query.whooshee_search(q).paginate(page, per_page)
#     results = pagination.items
#     return render_template('main/search.html', q=q, results=results, pagination=pagination, category=category)

blog/blueprints/user.py
from flask import render_template, Blueprint, current_app, request, flash, redirect, url_for
from flask_login import current_user, logout_user, login_required, fresh_login_required
from blog.models import User, Category, Post
from blog.extensions import db
from blog.forms.user import EditProfileForm, ChangePasswordForm, PostForm

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user and user.locked:
        flash('Your account is locked.', 'danger')

    if user == current_user and not user.active:
        logout_user()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(user).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, posts=posts)

@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        current_user.website = form.website.data
        current_user.location = form.location.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.bio.data = current_user.bio
    form.website.data = current_user.website
    form.location.data = current_user.location
    return render_template('user/settings/edit_profile.html', form=form)

@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('.index', username=current_user.username))
        flash('Invalid password.', 'warning')
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category, author=current_user)
        # same with:
        # category_id = form.category.data
        # post = Post(title=title, body=body, category_id=category_id)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('main.show_post', post_id=post.id))
    return render_template('user/new_post.html', form=form)

blog/templates/main/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('main.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('main.show_post', post_id=post.id) }}">Read More</a></small>
        </p>
        <small>
            Comments: <a href="{{ url_for('main.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a href="{{ url_for('main.show_category', category_id=post.category.id) }}">
            {{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }} </span>
            Author: <a href="{{ url_for('user.index', username=post.author.username) }}">{{ post.author.username}}</a>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('user.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

blog/templates/main/_sidebar.html
{% if links %}
    <div class="card mb-3">
        <div class="card-header">Links</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if categories %}
    <div class="card mb-3">
        <div class="card-header">Categories</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<aside id="kratos_about-2" class="widget amadeus_about clearfix">
    <div class="photo-background">
        <div class="photo-background" style="background:url(http://img.yyf-blog.com/bg.jpg) no-repeat center center; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
        </div>
    </div>
    <div class="photo-wrapper clearfix">
        <div class="photo-wrapper-tip text-center">
            <img class="about-photo" src="http://img.yyf-blog.com/avater.png" />
        </div>
    </div>
    <div class="textwidget">
        <p class="text-center">😀 西南交通大学 <br />利兹学院计算机</p>
    </div>
</aside>

blog/templates/main/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Category: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} posts</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "main/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "main/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/main/edit_post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Edit Post{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Edit Post</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

blog/templates/main/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">Hello,{% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'main/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pager(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'main/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/main/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}
            <span class="float-right">
        {% if current_user == post.author or current_user.can('MODERATE') %}
            <a class="btn btn-info btn-sm" href="{{ url_for('.edit_post', post_id=post.id) }}">Edit</a>
            <form class="inline" method="post"
                  action="{{ url_for('main.delete_post', post_id=post.id, next=url_for('main.index')) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete
                </button>
            </form>
        {% endif %}
      </span>
        </h1>
        <small>
            Category: <a
{#                href="{{ url_for('.show_category', category_id=post.category.id) }}"#}
        >{{ post.category.name }}</a><br>
            Date: {{ moment(post.timestamp).format('LL') }}<br>
            Author: {{ post.author.username }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">Share
            </button>
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Permalink</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments" id="comments">
                <h3>{{ comments|length }} Comments
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            latest</a>
                    </small>
                    {% if current_user.can('MODERATE')%}
                        <form class="float-right" method="post"
                              action="{{ url_for('.set_comment', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if post.can_comment %}Disable{% else %}Enable{% endif %} Comment
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a target="_blank">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author.name }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-primary">Author</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                        {{ moment(comment.timestamp).fromNow() }}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                                    {% if current_user.is_authenticated %}
                                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                                        {% if current_user.can('MODERATE')%}
                                        <form class="inline" method="post"
                                              action="{{ url_for('.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Are you sure?');">Delete
                                            </button>
                                        {% endif %}
                                        </form>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>No comments.</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-dark">
                    Reply:
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
                </div>
            {% endif %}
            {% if post.can_comment %}
                {% if current_user.can('COMMENT') %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
                {% endif %}
            {% else %}
                <div class="tip"><h5>Comment disabled.</h5></div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "main/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/main/search.html
{#{% extends 'base.html' %}#}
{#{% from 'bootstrap/pagination.html' import render_pagination %}#}
{#{% from 'macros.html' import photo_card, user_card with context %}#}
{#{% block title %}Search: {{ q }}{% endblock %}#}
{##}
{#{% block content %}#}
{#    <div class="page-header">#}
{#        <h1>Search: {{ q }}</h1>#}
{#    </div>#}
{#    <div class="row">#}
{#        <div class="col-md-3">#}
{#            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">#}
{#                <a class="nav-item nav-link {% if category == 'user' %}active{% endif %}"#}
{#                   href="{{ url_for('.search', q=q, category='user') }}">User</a>#}
{#                <a class="nav-item nav-link {% if category == 'post' %}active{% endif %}"#}
{#                   href="{{ url_for('.search', q=q, category='post') }}">Post</a>#}
{#                <a class="nav-item nav-link {% if category == 'comment' %}active{% endif %}"#}
{#                   href="{{ url_for('.search', q=q, category='comment') }}">Comment</a>#}
{#            </div>#}
{#        </div>#}
{#        <div class="col-md-9">#}
{#            {% if results %}#}
{#                <h5>{{ results|length }} results</h5>#}
{#                {% for item in results %}#}
{#                    {% if category == 'post' %}#}
{#                        {{ item }}#}
{#                        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=item.id) }}">{{ item.title }}</a></h3>#}
{#                        <p>#}
{#                            {{ item.body|striptags|truncate }}#}
{#                            <small><a href="{{ url_for('.show_post', post_id=item.id) }}">Read More</a></small>#}
{#                        </p>#}
{#                    {% elif category == 'user' %}#}
{#                        {{ user_card(item) }}#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#            {% else %}#}
{#                <h5 class="tip">No results.</h5>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#    {% if results %}#}
{#        <div class="page-footer">#}
{#            {{ render_pagination(pagination, align='right') }}#}
{#        </div>#}
{#    {% endif %}#}
{#{% endblock %}#}