blog/blueprints/admin.py
from flask import render_template, flash, Blueprint, request, current_app, redirect, url_for
from flask_login import login_required

from blog.decorators import admin_required, permission_required
from blog.extensions import db
from blog.forms.admin import EditProfileAdminForm
from blog.forms.auth import CategoryForm
from blog.models import Role, User, Comment, Post, Category
from blog.utils import redirect_back

admin_bp = Blueprint('admin', __name__)

@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
    user_count = User.query.count()
    locked_user_count = User.query.filter_by(locked=True).count()
    blocked_user_count = User.query.filter_by(active=False).count()
    post_count = Post.query.count()
    comment_count = Comment.query.count()
    category_count = Category.query.count()
    reported_comments_count = Comment.query.filter(Comment.flag > 0).count()
    return render_template('admin/index.html', user_count=user_count, post_count=post_count, comment_count=comment_count, locked_user_count=locked_user_count,
                           blocked_user_count=blocked_user_count, reported_comments_count=reported_comments_count,category_count=category_count
                           )


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
    user = User.query.get_or_404(user_id)
    form = EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.name = form.name.data
        role = Role.query.get(form.role.data)
        if role.name == 'Locked':
            user.lock()
        user.role = role
        user.bio = form.bio.data
        user.website = form.website.data
        user.confirmed = form.confirmed.data
        user.active = form.active.data
        user.location = form.location.data
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect_back()
    form.name.data = user.name
    form.role.data = user.role_id
    form.bio.data = user.bio
    form.website.data = user.website
    form.location.data = user.location
    form.username.data = user.username
    form.email.data = user.email
    form.confirmed.data = user.confirmed
    form.active.data = user.active
    return render_template('admin/edit_profile.html', form=form, user=user)


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
    user = User.query.get_or_404(user_id)
    user.block()
    flash('Account blocked.', 'info')
    return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unblock()
    flash('Block canceled.', 'info')
    return redirect_back()


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.lock()
    flash('Account locked.', 'info')
    return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
    user = User.query.get_or_404(user_id)
    user.unlock()
    flash('Lock canceled.', 'info')
    return redirect_back()

@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
    filter_rule = request.args.get('filter', 'all')  # 'all', 'locked', 'blocked', 'administrator', 'moderator'
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_USER_PER_PAGE']
    administrator = Role.query.filter_by(name='Administrator').first()
    moderator = Role.query.filter_by(name='Moderator').first()

    if filter_rule == 'locked':
        filtered_users = User.query.filter_by(locked=True)
    elif filter_rule == 'blocked':
        filtered_users = User.query.filter_by(active=False)
    elif filter_rule == 'administrator':
        filtered_users = User.query.filter_by(role=administrator)
    elif filter_rule == 'moderator':
        filtered_users = User.query.filter_by(role=moderator)
    else:
        filtered_users = User.query

    pagination = filtered_users.order_by(User.member_since.desc()).paginate(page, per_page)
    users = pagination.items
    return render_template('admin/manage_user.html', pagination=pagination, users=users)


# @admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
# @admin_bp.route('/manage/photo/<order>')
# @login_required
# @permission_required('MODERATE')
# def manage_post(order):
#     page = request.args.get('page', 1, type=int)
#     per_page = current_app.config['ALBUMY_MANAGE_PHOTO_PER_PAGE']
#     order_rule = 'flag'
#     if order == 'by_time':
#         pagination = Photo.query.order_by(Photo.timestamp.desc()).paginate(page, per_page)
#         order_rule = 'time'
#     else:
#         pagination = Photo.query.order_by(Photo.flag.desc()).paginate(page, per_page)
#     photos = pagination.items
#     return render_template('admin/manage_photo.html', pagination=pagination, photos=photos, order_rule=order_rule)

@admin_bp.route('/manage/post')
@login_required
@permission_required('MODERATE')
def manage_post():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
        page, per_page=current_app.config['BLOG_MANAGE_POST_PER_PAGE'])
    posts = pagination.items
    return render_template('admin/manage_post.html', page=page, pagination=pagination, posts=posts)


@admin_bp.route('/manage/category')
@login_required
@permission_required('MODERATE')
def manage_category():
    categories = Category.query.all()
    return render_template('admin/manage_category.html', categories=categories)

@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        category = Category(name=name)
        db.session.add(category)
        db.session.commit()
        flash('Category created.', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)

@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
@permission_required('MODERATE')
def edit_category(category_id):
    form = CategoryForm()
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not edit the default category.', 'warning')
        return redirect(url_for('blog.index'))
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('Category updated.', 'success')
        return redirect(url_for('.manage_category'))

    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    if category.id == 1:
        flash('You can not delete the default category.', 'warning')
        return redirect(url_for('.manage_category'))
    category.delete()
    flash('Category deleted.', 'success')
    return redirect(url_for('.manage_category'))

@admin_bp.route('/manage/comment')
@login_required
@permission_required('MODERATE')
def manage_comment():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', pagination=pagination, comments=comments)

blog/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user, login_fresh, confirm_login

# from blog.emails import send_confirm_email, send_reset_password_email
from blog.extensions import db
from blog.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm, PostForm
from blog.models import User, Category, Post
# from blog.settings import Operations
from blog.utils import redirect_back
# from blog.utils import generate_token, validate_token
auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data.lower()).first()
        if user is not None and user.validate_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash('Login success.', 'info')
            return redirect_back()
        flash('Invalid email or password.', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        email = form.email.data.lower()
        username = form.username.data
        password = form.password.data
        user = User(name=name, email=email, username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        # token = generate_token(user=user, operation='confirm')
        # send_confirm_email(user=user, token=token)
        flash('Register successfully.', 'info')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


# @auth_bp.route('/confirm/<token>')
# @login_required
# def confirm(token):
#     if current_user.confirmed:
#         return redirect(url_for('main.index'))
#
#     if validate_token(user=current_user, token=token, operation=Operations.CONFIRM):
#         flash('Account confirmed.', 'success')
#         return redirect(url_for('main.index'))
#     else:
#         flash('Invalid or expired token.', 'danger')
#         return redirect(url_for('.resend_confirm_email'))
#
#
# @auth_bp.route('/resend-confirm-email')
# @login_required
# def resend_confirm_email():
#     if current_user.confirmed:
#         return redirect(url_for('main.index'))
#
#     token = generate_token(user=current_user, operation=Operations.CONFIRM)
#     send_confirm_email(user=current_user, token=token)
#     flash('New email sent, check your inbox.', 'info')
#     return redirect(url_for('main.index'))
#
#
# @auth_bp.route('/forget-password', methods=['GET', 'POST'])
# def forget_password():
#     if current_user.is_authenticated:
#         return redirect(url_for('main.index'))
#
#     form = ForgetPasswordForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data.lower()).first()
#         if user:
#             token = generate_token(user=user, operation=Operations.RESET_PASSWORD)
#             send_reset_password_email(user=user, token=token)
#             flash('Password reset email sent, check your inbox.', 'info')
#             return redirect(url_for('.login'))
#         flash('Invalid email.', 'warning')
#         return redirect(url_for('.forget_password'))
#     return render_template('auth/reset_password.html', form=form)

#
# @auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
# def reset_password(token):
#     if current_user.is_authenticated:
#         return redirect(url_for('main.index'))
#
#     form = ResetPasswordForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data.lower()).first()
#         if user is None:
#             return redirect(url_for('main.index'))
#         if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD,
#                           new_password=form.password.data):
#             flash('Password updated.', 'success')
#             return redirect(url_for('.login'))
#         else:
#             flash('Invalid or expired link.', 'danger')
#             return redirect(url_for('.forget_password'))
#     return render_template('auth/reset_password.html', form=form)

@auth_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('show_post', post_id=post.id))
    return render_template('new_post.html', form=form)

blog/blueprints/user.py
from flask import render_template, Blueprint, current_app, request, flash, redirect, url_for
from flask_login import current_user, logout_user, login_required, fresh_login_required
from blog.models import User, Category, Post
from blog.extensions import db
from blog.forms.user import EditProfileForm, ChangePasswordForm, PostForm

user_bp = Blueprint('user', __name__)


@user_bp.route('/<username>')
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    if user == current_user and user.locked:
        flash('Your account is locked.', 'danger')

    if user == current_user and not user.active:
        logout_user()

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(user).order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('user/index.html', user=user, pagination=pagination, posts=posts)

@user_bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        current_user.website = form.website.data
        current_user.location = form.location.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.bio.data = current_user.bio
    form.website.data = current_user.website
    form.location.data = current_user.location
    return render_template('user/settings/edit_profile.html', form=form)

@user_bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.set_password(form.password.data)
            db.session.commit()
            flash('Password updated.', 'success')
            return redirect(url_for('.index', username=current_user.username))
        flash('Invalid password.', 'warning')
    return render_template('user/settings/change_password.html', form=form)


@user_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        post = Post(title=title, body=body, category=category, author=current_user)
        # same with:
        # category_id = form.category.data
        # post = Post(title=title, body=body, category_id=category_id)
        db.session.add(post)
        db.session.commit()
        flash('Post created.', 'success')
        return redirect(url_for('main.show_post', post_id=post.id))
    return render_template('user/new_post.html', form=form)

blog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block head %}
        <title>{% block title %}{% endblock %} - Blog</title>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        {% block styles %}
            <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='open-iconic/font/css/open-iconic-bootstrap.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
            <link rel="stylesheet" href="{{ url_for('static', filename='css/mycss.css') }}">
        {% endblock styles %}
    {% endblock head %}
</head>

<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                <img src="{{ url_for('static', filename='favicon.ico') }}" alt="Blog">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {{ render_nav_item('main.index', 'Home') }}
{#                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">#}
{#                        <input type="text" name="q" class="form-control mr-sm-1" placeholder="Post"#}
{#                               required>#}
{#                        <button class="btn btn-light my-2 my-sm-0" type="submit">#}
{#                            <span class="oi oi-magnifying-glass"></span>#}
{#                        </button>#}
{#                    </form>#}
                </div>
                <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            {{ current_user.name }}<span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                            <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                <span class="oi oi-person"></span> My Home
                            </a>
                            <div class="dropdown-divider"></div>
                             <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                <span class="oi oi-cog"></span> Settings
                            </a>
                            {% if current_user.can('POST') %}
                                <a class="dropdown-item" href="{{ url_for('user.new_post') }}">
                                    <span class="oi oi-book"></span> New Post
                                </a>
                            {% endif %}
                            {% if current_user.can('MODERATE') %}
                                <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                    <span class="oi oi-dashboard"></span> Dashboard
                                </a>
                            {% endif %}
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-primary" href="{{ url_for('auth.login') }}">Login</a>&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{{ url_for('auth.register') }}">Join Us</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>
{% endblock %}

<main>
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="alert alert-{{ message[0] }}">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message[1] }}
            </div>
        {% endfor %}
        {% block content %}{% endblock %}
        {% block footer %}
            <footer>
                <p class="float-left">
                    <small>&copy; 2018
                        <a href="http://xuedifan.pythonanywhere.com/" title="Written by Xue Difan">Difan Xue</a> -
                        <a href="https://github.com/xue000" title="Fork me on GitHub">GitHub</a> -
                        <a href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
                    </small>
                </p>
                <p class="float-right">
                    <small>Share your knowledge.</small>
                </p>
            </footer>
        {% endblock %}
    </div>
</main>

{% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
{% endblock %}
</body>
</html>